import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Page_components/Navbar/Navbar";
import Client_Rapper from "./Client_Rapper";
import Footer from "@/components/Page_components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font" cz-shortcut-listen="true">
        <Client_Rapper>
          <header>
            <Navbar />
          </header>
          {children}
          <Footer />
        </Client_Rapper>
      </body>
    </html>
  );
}
